#pragma once

#include "runtime/KeyEvent.h"
#include <string>

// carefully selected to match Linux keys: /usr/include/linux/input-event-codes.h
enum class Key : KeyCode {
  None           = no_key,
  Esc            = 1,
  _1             = 2,
  _2             = 3,
  _3             = 4,
  _4             = 5,
  _5             = 6,
  _6             = 7,
  _7             = 8,
  _8             = 9,
  _9             = 10,
  _0             = 11,
  Minus          = 12,
  Equal          = 13,
  Backspace      = 14,
  Tab            = 15,
  Q              = 16,
  W              = 17,
  E              = 18,
  R              = 19,
  T              = 20,
  Y              = 21,
  U              = 22,
  I              = 23,
  O              = 24,
  P              = 25,
  LeftBrace      = 26,
  RightBrace     = 27,
  Enter          = 28,
  LeftCtrl       = 29,
  A              = 30,
  S              = 31,
  D              = 32,
  F              = 33,
  G              = 34,
  H              = 35,
  J              = 36,
  K              = 37,
  L              = 38,
  Semicolon      = 39,
  Apostrophe     = 40,
  Grave          = 41,
  LeftShift      = 42,
  Backslash      = 43,
  Z              = 44,
  X              = 45,
  C              = 46,
  V              = 47,
  B              = 48,
  N              = 49,
  M              = 50,
  Comma          = 51,
  Dot            = 52,
  Slash          = 53,
  RightShift     = 54,
  KPAsterisk     = 55,
  LeftAlt        = 56,
  Space          = 57,
  CapsLock       = 58,
  F1             = 59,
  F2             = 60,
  F3             = 61,
  F4             = 62,
  F5             = 63,
  F6             = 64,
  F7             = 65,
  F8             = 66,
  F9             = 67,
  F10            = 68,
  NumLock        = 69,
  ScrollLock     = 70,
  KP7            = 71,
  KP8            = 72,
  KP9            = 73,
  KPMinus        = 74,
  KP4            = 75,
  KP5            = 76,
  KP6            = 77,
  KPPlus         = 78,
  KP1            = 79,
  KP2            = 80,
  KP3            = 81,
  KP0            = 82,
  KPDot          = 83,
  _102nd         = 86,
  F11            = 87,
  F12            = 88,
  KPEnter        = 96,
  RightCtrl      = 97,
  KPSlash        = 98,
  SysRQ          = 99,
  RightAlt       = 100,
  Home           = 102,
  Up             = 103,
  PageUp         = 104,
  Left           = 105,
  Right          = 106,
  End            = 107,
  Down           = 108,
  PageDown       = 109,
  Insert         = 110,
  Delete         = 111,
  Mute           = 113,
  VolumeDown     = 114,
  VolumeUp       = 115,
  KPEqual        = 117,
  Pause          = 119,
  KPComma        = 121,
  LeftMeta       = 125,
  RightMeta      = 126,
  Compose        = 127,
  WWW            = 150,
  Mail           = 155,
  Back           = 158,
  Forward        = 159,
  NextSong       = 163,
  PlayPause      = 164,
  PreviousSong   = 165,
  BrightnessDown = 224,
  BrightnessUp   = 225,

  Any            = any_key,
  Shift,
  Ctrl,
  Meta,
  Virtual1       = first_virtual_key,
  Virtual2,
  Virtual3,
  Virtual4,
  Virtual5,
  Virtual6,
  Virtual7,
  Virtual8,

  Count,
};

const char* get_key_name(const Key& key);
Key get_key_by_name(const std::string& key_name);
KeyCode operator*(Key key);
